services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    #platform: linux/amd64
    container_name: ollama
    profiles:
      - open-webui
      - ollama
    depends_on:
      - caddy
    restart: on-failure:5
    tty: true
    volumes:
      - ollama:/root/.ollama
    # ports:
    #   - ${OLLAMA_PORT-11434}:11434
    env_file:
      - ./env/ollama.env
    security_opt:
      - no-new-privileges:true
    networks:
      - open-webui-network
    devices:
      - /dev/dri
      - /dev/kfd

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    profiles:
      - open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
      - caddy
    env_file:
      - ./env/open-webui.env
    #environment:
    #  - UID=${PUID:-1000}
    #  - GID=${PGID:-1000}
    # ports:
    #   - ${OPEN_WEBUI_PORT-3000}:8080
    restart: on-failure:5
    networks:
      - open-webui-network
    security_opt:
      - no-new-privileges:true

volumes:
  ollama: {}
  open-webui: {}

networks:
  open-webui-network:
    driver: bridge
    name: open-webui-network
