name: openwebui

services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    container_name: ollama
    profiles:
      - openwebui
      - ollama
    depends_on:
      - caddy
    restart: on-failure:7
    tty: true
    volumes:
      - ollama:/root/.ollama
    # ports:
    #   - ${OLLAMA_PORT-11434}:11434
    env_file:
      - ./env/ollama.env
    environment:
      - TZ=${TZ:-Europe/Paris}
    security_opt:
      - no-new-privileges:true
    networks:
      - openwebui-internal
    # devices:
    #   - /dev/dri
    #   - /dev/kfd

  openwebui-postgres:
    image: postgres:17-alpine
    container_name: openwebui-postgres
    profiles:
      - openwebui
    env_file:
      - ./env/openwebui-postgres.env
    environment:
      - TZ=${TZ:-Europe/Paris}
    volumes:
      - openwebui-postgres:/var/lib/postgresql/data
    restart: on-failure:7
    networks:
      - openwebui-internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   profiles:
  #     - openwebui
    # env_file:
    #   - ./env/openwebui-pgadmin.env
  #   volumes:
  #     - openwebui-pgadmin:/var/lib/pgadmin
  #   restart: on-failure:7
  #   depends_on:
  #     openwebui-postgres:
  #       condition: service_healthy
  #   networks:
  #     - openwebui-network


  openwebui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: openwebui
    profiles:
      - openwebui
    volumes:
      - openwebui:/app/backend/data
    depends_on:
      - ollama
      - caddy
      - openwebui-postgres
    env_file:
      - ./env/openwebui.env
    environment:
      - TZ=${TZ:-Europe/Paris}
    #  - UID=${PUID:-1000}
    #  - GID=${PGID:-1000}
    # ports:
    #   - ${OPEN_WEBUI_PORT-3000}:8080
    restart: on-failure:7
    networks:
      - caddy-ai
      - openwebui-internal
    security_opt:
      - no-new-privileges:true

volumes:
  ollama: {}
  openwebui: {}
  openwebui-postgres: {}
  openwebui-pgadmin: {}

networks:
  caddy-ai:
    driver: bridge
    name: caddy-ai
  openwebui-internal:
    driver: bridge
    name: openwebui-internal
