services:
  # fleet
  fleet:
    image: lscr.io/linuxserver/fleet:latest
    container_name: fleet
    profiles:
      - fleet
    restart: on-failure:5
    depends_on:
      - caddy
      - fleet_db
    env_file:
      - ./fleet/env/fleet.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - fleet_config:/config
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true

  fleet_db:
    image: mariadb:latest
    container_name: fleet_db
    profiles:
      - database
      - fleet
    depends_on:
      - caddy
    restart: on-failure:5
    volumes:
      - fleet_db:/var/lib/mysql:rw
    env_file:
      - ./fleet/env/fleet_db.env
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true


volumes:
  fleet_config:
    name: fleet_config
  fleet_db:
    name: fleet_db