settings:
  log:
    level: DEBUG
defaults:
  service:
    latest_version:
      access_token: <secret>
    deployed_version:
      allow_invalid_certs: true
notify:
  default_gotify:
    type: gotify
    url_fields:
      host: gotify.example.io
      token: <secret>
  default_mattermost:
    type: mattermost
    url_fields:
      host: localhost
      port: "8081"
      token: <secret>
webhook:
  awx_more:
    type: github
    url: http://localhost:8081
    secret: <secret>
    silent_fails: true
  awx_other:
    type: github
    url: https://localhost:8081/api/v2/job_templates/36/github/
    secret: <secret>
    silent_fails: true
service:
  forgejo:
    latest_version:
      type: url
      url: https://code.forgejo.org/api/v1/repos/forgejo/forgejo/releases
      url_commands:
        - type: regex
          regex: "['\"]tag_name['\"]: *['\"]v?([0-9.]+(?:-dev)?)['\"]"
    deployed_version:
      type: url
      url: https://code.forgejo.org
      regex: Powered by Forgejo.*\s+Version:\s+([0-9.]+(?:-dev)?)
    dashboard:
      web_url: https://codeberg.org/forgejo/forgejo/src/branch/forgejo/release-notes-published/{{ version }}.md
      icon: https://code.forgejo.org/assets/img/logo.svg
      tags:
        - go
  svt-av1:
    latest_version:
      type: url
      url: https://gitlab.com/api/v4/projects/AOMediaCodec%2FSVT-AV1/repository/tags?order_by=version&sort=desc
      url_commands:
        - type: regex
          regex: '"name":"v?([0-9.]+(?:-rc[0-9]+)?)"'
    dashboard:
      icon: https://upload.wikimedia.org/wikipedia/commons/8/84/AV1_logo_2018.svg
      web_url: https://gitlab.com/AOMediaCodec/SVT-AV1/-/releases/v{{ version }}
    tags:
      - av1
      - video
      - encoder
  ffmpeg:
    latest_version:
      type: url
      url: https://api.github.com/repos/FFmpeg/FFmpeg/tags
      url_commands:
        - type: regex
          regex: '"name":"n?([0-9.]+)"'
    dashboard:
      icon: https://upload.wikimedia.org/wikipedia/commons/7/76/FFmpeg_icon.svg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original
      web_url: https://github.com/FFmpeg/FFmpeg/releases/tag/n{{ version }}
  qbittorrent:
    latest_version:
      type: url
      url: https://api.github.com/repos/qbittorrent/qBittorrent/releases/latest
      url_commands:
        - type: regex
          regex: '"tag_name":"release-([0-9.]+)"'
    dashboard:
      icon: https://upload.wikimedia.org/wikipedia/commons/6/66/New_qBittorrent_Logo.svg
      web_url: https://github.com/qbittorrent/qBittorrent/releases/tag/release-{{ version }}
    tags:
      - bittorrent
      - qt
      - cplusplus