name: localai

services:
  # localai
  localai:
    image: localai/localai:${LOCALAI_DOCKER_TAG:-latest}
    container_name: localai
    profiles:
      - localai
    extends:
      file: ../../common.yml
      service: service-base
    depends_on:
      - caddy
    env_file:
      - ./env/localai.env
    volumes:
      - localai_data:/data
      - localai_models:/models
      - localai_backends:/backends
      - localai_config:/config
    networks:
      - caddy-ai

volumes:
  localai_models:
    name: localai_models
  localai_backends:
    name: localai_backends
  localai_config:
    name: localai_config
  localai_data:
    name: localai_data

networks:
  caddy-ai:
    driver: bridge
    name: caddy-ai
