services:
  # cyberchef
  cyberchef0:
    image: mpepping/cyberchef:latest
    container_name: cyberchef0
    profiles:
      - cyberchef
    restart: on-failure:5
    depends_on:
      - caddy
    networks:
      - infra-network
    read_only: false
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - SYS_ADMIN

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.001'
          memory: 20M

  cyberchef1:
    image: mpepping/cyberchef:latest
    container_name: cyberchef1
    profiles:
      - cyberchef
    restart: on-failure:5
    depends_on:
      - caddy
    networks:
      - infra-network
    read_only: false
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - SYS_ADMIN

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.001'
          memory: 20M
