services:
  # cyberchef
  cyberchef0:
    image: mpepping/cyberchef:latest
    container_name: cyberchef0
    profiles:
      - cyberchef
    restart: on-failure:7
    depends_on:
      - caddy
    networks:
      - caddy-tools
    read_only: false
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - SYS_ADMIN

  cyberchef1:
    image: mpepping/cyberchef:latest
    container_name: cyberchef1
    profiles:
      - cyberchef
    restart: on-failure:7
    depends_on:
      - caddy
    networks:
      - caddy-tools
    read_only: false
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - SYS_ADMIN

networks:
  caddy-tools:
    driver: bridge
    name: caddy-tools
