services:
  # cyberchef
  cyberchef0:
    extends:
      file: ../../common.yml
      service: service-base
    image: mpepping/cyberchef:${CYBERCHEF_DOCKER_TAG:-latest}
    container_name: cyberchef0
    profiles:
      - cyberchef
    depends_on:
      - caddy
    networks:
      - caddy-tools
    read_only: false

  cyberchef1:
    extends:
      file: ../../common.yml
      service: service-base
    image: mpepping/cyberchef:${CYBERCHEF_DOCKER_TAG:-latest}
    container_name: cyberchef1
    profiles:
      - cyberchef
    depends_on:
      - caddy
    networks:
      - caddy-tools
    read_only: false

networks:
  caddy-tools:
    driver: bridge
    name: caddy-tools
