services:
  # psitransfer
  psitransfer:
    image: psitrax/psitransfer:latest
    container_name: psitransfer
    profiles:
      - psitransfer
    restart: on-failure:5
    depends_on:
      - caddy
    env_file:
      - env/psitransfer.env
    volumes:
      - psitransfer_data:/data
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true

volumes:
  psitransfer_data:
    name: psitransfer_data