version: "3.9"

volumes:
  certbot-cert:
    name: certbot-cert
  wordpress:
    name: wordpress
  dbdata:
    name: dbdata
  qbittorrent-downloads:
    name: qbittorrent-downloads
  qbittorrent-conf:
    name: qbittorrent-conf
  jellyfin-config:
    name: jellyfin-config
  jellyfin-tvseries:
    name: jellyfin-tvseries
  jellyfin-movies:
    name: jellyfin-movies
  jellyfin:
    name: jellyfin
  postgres-data:
    name: postgres-data
