version: "3.9"

volumes:
  qbittorrent-downloads:
    name: qbittorrent-downloads
  qbittorrent-conf:
    name: qbittorrent-conf
  jellyfin-config:
    name: jellyfin-config
  jellyfin-tvseries:
    name: jellyfin-tvseries
  jellyfin-movies:
    name: jellyfin-movies
  jellyfin:
    name: jellyfin
