version: "3.9"

services:
  wp_db:
    image: mariadb:10.10.3
    container_name: wp_db
    profiles:
      - wp_db
    restart: unless-stopped
    env_file: 
      - env/wp_database.env
    volumes: 
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    security_opt:
      - no-new-privileges:true

  wordpress:
    depends_on: 
      - wp_db
    image: wordpress:6.2.0-fpm
    container_name: wordpress
    profiles:
      - wordpress
    restart: unless-stopped
    env_file: 
      - env/wordpress.env
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
    security_opt:
      - no-new-privileges:true
#    cap_drop:
#        - ALL
#    cap_add:
#      - SETUID
#      - SETGID
#      - DAC_OVERRIDE
#      - NET_BIND_SERVICE
#      - NET_RAW
#      - CAP_CHOWN
  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    profiles:
      - phpmyadmin
    restart: unless-stopped
    env_file: 
      - env/phpmyadmin.env
    depends_on:
      - wp_db
    networks:
      - app-network
    security_opt:
      - no-new-privileges:true

volumes:
  wordpress:
    name: wordpress
  dbdata:
    name: dbdata