version: "3.9"

services:
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot:v1.32.0
    container_name: certbot
    profiles:
      - certbot
    volumes:
      - certbot-cert:/etc/letsencrypt
      - wordpress:/var/www/wordpress
      - jellyfin:/var/www/jellyfin
    #command: >
    #  certonly --email bensuperpc@bensuperpc.fr --agree-tos --rsa-key-size 4096 --no-eff-email --verbose --noninteractive --staging --webroot
    #  --webroot-path=/var/www/wordpress --domain bensuperpc.org --domain www.bensuperpc.org
    #  --webroot-path=/var/www/jellyfin --domain jellyfin.bensuperpc.org --domain www.jellyfin.bensuperpc.org 

    #command: >
    #  certonly --email bensuperpc@bensuperpc.fr --agree-tos --rsa-key-size 4096 --no-eff-email --verbose --noninteractive --force-renewal --webroot
    #  --webroot-path=/var/www/wordpress --domain bensuperpc.org --domain www.bensuperpc.org
    #  --webroot-path=/var/www/jellyfin --domain jellyfin.bensuperpc.org --domain www.jellyfin.bensuperpc.org

    command: >
      certonly --email bensuperpc@bensuperpc.fr --agree-tos --rsa-key-size 4096 --no-eff-email --verbose --noninteractive --keep-until-expiring --webroot 
      --webroot-path=/var/www/wordpress --domain bensuperpc.org --domain www.bensuperpc.org
      --webroot-path=/var/www/jellyfin --domain jellyfin.bensuperpc.org --domain www.jellyfin.bensuperpc.org

volumes:
  certbot-cert:
    name: certbot-cert