services:
  # Backup
  backup:
    image: cupcakearmy/autorestic:latest
    container_name: backup
    profiles:
      - backup
    restart: on-failure:5
    env_file:
      - env/backup.env
    #entrypoint: ["autorestic", "backup", "--ci", "-va", "-c", "/data/autorestic.yml"]
    entrypoint: ["restic init --repository-version 2 --repo", "/data/caddy_data"]
    volumes:
      - backup:/backup
      - ./config/backup/autorestic.yml:/data/autorestic.yml:ro
      - caddy_data:/data/caddy_data:ro
      - caddy_config:/data/caddy_config:ro
#      - gitea_data:/data/gitea_data:ro
#      - gitea_config:/data/gitea_config:ro
#      - wordpress_db:/data/wordpress_db:ro
#      - wordpress:/data/wordpress:ro
#      - jellyfin_config:/data/jellyfin_config:ro
#      - jellyfin_data:/data/jellyfin_data:ro
#      - jellyfin_cache:/data/jellyfin_cache:ro
#      - qbittorrent_config:/data/qbittorrent_config:ro
#      - qbittorrent_data:/data/qbittorrent_data:ro
#      - uptimekuma_data:/data/uptimekuma_data:ro
    security_opt:
      - no-new-privileges:true

volumes:
  backup:
    name: backup