services:
  # openssh
  openssh:
    image: linuxserver/openssh-server:latest
    container_name: openssh
    profiles:
      - openssh
    depends_on:
      - caddy
    restart: on-failure:5
    env_file:
      - ./openssh/env/openssh.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - openssh_config:/config
      - public_data:/public
      - private_data:/private
      - ./openssh/config/authorized_keys:/authorized_ssh_keys:ro
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true
    ports:
      - 2222:2222
volumes:
  openssh_config:
    name: openssh_config
  public_data:
    name: public_data
  private_data:
    name: private_data
