services:
  # openssh
  openssh:
    image: linuxserver/openssh-server:latest
    container_name: openssh
    profiles:
      - openssh
    depends_on:
      - caddy
    restart: on-failure:5
    env_file:
      - ./openssh/env/openssh.env
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - openssh_config:/config
      - ./openssh/config/authorized_keys:/authorized_ssh_keys:ro
      - public_data:/public
      - private_data:/private
      - caddy_data:/caddy_data:rw
      - caddy_config:/caddy_config:rw
      - caddy_backup:/caddy_backup:rw
      - caddy_backup_cache:/caddy_backup_cache:rw
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true
    ports:
      - 2222:2222
volumes:
  openssh_config:
    name: openssh_config
  public_data:
    name: public_data
  private_data:
    name: private_data
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
  caddy_backup:
    name: caddy_backup
  caddy_backup_cache:
    name: caddy_backup_cache

