services:
  # Uptime Kuma
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    profiles:
      - uptime-kuma
    volumes:
      - uptimekuma_data:/app/data
    environment:
      - TZ=${TZ:-Europe/Paris}
    restart: on-failure:7
    depends_on:
      - caddy
    networks:
      - caddy-infra
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - SYS_ADMIN

volumes:
  uptimekuma_data:
    name: uptimekuma_data

networks:
  caddy-infra:
    driver: bridge
    name: caddy-infra
