services:
  # dozzle
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    profiles:
      - dozzle
    restart: on-failure:5
    depends_on:
      - caddy
    env_file:
      - ./dozzle/env/dozzle.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true
