services:
  # it-tools
  it-tools0:
    image: ghcr.io/sharevb/it-tools:latest
    container_name: it-tools0
    profiles:
      - it-tools
    restart: on-failure:7
    depends_on:
      - caddy
    networks:
      - caddy-tools
    read_only: false
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - SYS_ADMIN
    environment:
      - TZ=${TZ:-Europe/Paris}

  it-tools1:
    image: ghcr.io/sharevb/it-tools:latest
    container_name: it-tools1
    profiles:
      - it-tools
    restart: on-failure:7
    depends_on:
      - caddy
    networks:
      - caddy-tools
    read_only: false
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - SYS_ADMIN
    environment:
      - TZ=${TZ:-Europe/Paris}

networks:
  caddy-tools:
    driver: bridge
    name: caddy-tools
