services:
  # it-tools
  it-tools0:
    extends:
      file: ../common.yml
      service: service-base
    image: ghcr.io/sharevb/it-tools:latest
    container_name: it-tools0
    profiles:
      - it-tools
    depends_on:
      - caddy
    networks:
      - caddy-tools
    read_only: false

  it-tools1:
    extends:
      file: ../common.yml
      service: service-base
    image: ghcr.io/sharevb/it-tools:latest
    container_name: it-tools1
    profiles:
      - it-tools
    depends_on:
      - caddy
    networks:
      - caddy-tools
    read_only: false

networks:
  caddy-tools:
    driver: bridge
    name: caddy-tools
