services:
  # psitransfer
  psitransfer:
    image: psitrax/psitransfer:latest
    container_name: psitransfer
    profiles:
      - psitransfer
    restart: on-failure:7
#    user: ${PUID:-1000}:${PGID:-1000} 
    depends_on:
      - caddy
    env_file:
      - ./env/psitransfer.env
    environment:
      - TZ=${TZ:-Europe/Paris}
    volumes:
      - psitransfer_data:/data
    networks:
      - psitransfer-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.001'
          memory: 20M

volumes:
  psitransfer_data:
    name: psitransfer_data

networks:
  psitransfer-network:
    driver: bridge
    name: psitransfer-network