services:
  # syncthing
  syncthing:
    image: linuxserver/syncthing:${SYNCTHING_DOCKER_TAG:-latest}
    container_name: syncthing
    profiles:
      - syncthing
    depends_on:
      - caddy
    extends:
      file: ../../common.yml
      service: service-base
    env_file:
      - ./env/syncthing.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - syncthing_config:/config
      - public_data:/data1
      - private_data:/data2
    networks:
      - caddy-media

volumes:
  syncthing_config:
    name: syncthing_config
  public_data:
    name: public_data
  private_data:
    name: private_data

networks:
  caddy-media:
    driver: bridge
    name: caddy-media
