services:
  # forgejo
  forgejo:
    image: codeberg.org/forgejo/forgejo:11-rootless
    container_name: forgejo
    profiles:
      - forgejo
    restart: on-failure:5
    depends_on:
      - database_forgejo
      - caddy
    ports:
      - "22:22"
    env_file:
      - ./env/forgejo.env
    volumes:
      - forgejo_data:/var/lib/gitea
      - forgejo_config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true
  
  # Database forgejo
  database_forgejo:
    image: mariadb:latest
    container_name: database_forgejo
    profiles:
      - forgejo
    depends_on:
      - caddy
    restart: on-failure:5
    volumes:
      - forgejo_db:/var/lib/mysql:rw
    env_file:
      - ./env/forgejo_db.env
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true

  # forgejo-runner
  docker-in-docker:
    image: code.forgejo.org/oci/docker:dind
    container_name: 'docker_dind'
    hostname: docker
    networks:
      - infra-network
    profiles:
      - forgejo
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
      DOCKER_HOST: docker-in-docker
    volumes:
      - forgejo_certs:/certs

  forgejo_runner:
    image: 'code.forgejo.org/forgejo/runner:6.3.1'
    networks:
      - infra-network
    profiles:
      - forgejo
    links:
      - docker-in-docker
    depends_on:
      docker-in-docker:
        condition: service_started
    container_name: 'forgejo_runner'
    env_file:
      - ./env/forgejo_runner.env
#    user: 1001:1001
    volumes:
#      - ./config/forgejo_runner/config.yaml:/config.yaml:ro
      - forgejo_runner:/data
      - forgejo_certs:/certs
    restart: 'unless-stopped'

#    command: '/bin/sh -c "while : ; do sleep 1 ; done ;"'
    command: '/bin/sh -c "sleep 5; forgejo-runner -c /data/config.yml daemon"'

volumes:
  forgejo_data:
    name: forgejo_data
  forgejo_config:
    name: forgejo_config
  forgejo_db:
    name: forgejo_db
  forgejo_certs:
    name: forgejo_certs
  forgejo_runner:
    name: forgejo_runner
