services:
  # dufs
  dufs:
    image: sigoden/dufs:latest
    container_name: dufs
    profiles:
      - dufs
    user: 1000:1000
    restart: on-failure:5
    depends_on:
      - caddy
    env_file:
      - ./dufs/env/dufs.env
    volumes:
      - public_data:/data
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true

volumes:
  public_data:
    name: public_data