services:
  # linkstack
  linkstack:
    image: linkstackorg/linkstack:latest
    container_name: linkstack
    profiles:
      - linkstack
    restart: on-failure:5
    depends_on:
      - caddy
    env_file:
      - ./linkstack/env/linkstack.env
    volumes:
      - linkstack_data:/htdocs
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.001'
          memory: 20M

volumes:
  linkstack_data:
    name: linkstack_data