services:
  main_infrastructure:
    container_name: main_infrastructure
    image: alpine:latest
    profiles:
      - main_infrastructure
    volumes:
      - infrastructure_server_chown:/infrastructure_server:rw
      - public_data:/infrastructure_server/public:rw
      - private_data:/infrastructure_server/private:rw
      #- caddy_data:/infrastructure_server/caddy_data:rw
      #- caddy_config:/infrastructure_server/caddy_config:rw
      #- caddy_backup:/infrastructure_server/caddy_backup:rw
      #- caddy_backup_cache:/infrastructure_server/caddy_backup_cache:rw
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
    # Fix root permissions on mounted volumes
    command: chown -R ${PUID:-1000}:${PGID:-1000} /infrastructure_server

volumes:
  infrastructure_server_chown:
    name: infrastructure_server_chown
  public_data:
    name: public_data
  private_data:
    name: private_data
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
  caddy_backup:
    name: caddy_backup
  caddy_backup_cache:
    name: caddy_backup_cache

networks:
  infra-network:
    driver: bridge
    name: infra-network