services:
  # syncthing
  syncthing:
    image: linuxserver/syncthing:latest
    container_name: syncthing
    profiles:
      - syncthing
    depends_on:
      - caddy
    restart: on-failure:5
    env_file:
      - ./syncthing/env/syncthing.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - syncthing_config:/config
      - public_data:/data1
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true

volumes:
  syncthing_config:
    name: syncthing_config
  public_data:
    name: public_data
