services:
  # stirlingpdf
  stirlingpdf:
    image: frooodle/s-pdf:${STIRLINGPDF_DOCKER_TAG:-latest}
    container_name: stirlingpdf
    profiles:
      - stirlingpdf
    extends:
      file: ../../common.yml
      service: service-base
    depends_on:
      - caddy
    env_file:
      - ./env/stirlingpdf.env
    volumes:
      - stirlingpdf_config:/configs
      - stirlingpdf_tessdata:/usr/share/tessdata
    networks:
      - caddy-tools
    read_only: false

volumes:
  stirlingpdf_config:
    name: stirlingpdf_config
  stirlingpdf_tessdata:
    name: stirlingpdf_tessdata

networks:
  caddy-tools:
    driver: bridge
    name: caddy-tools