services:
  # stirlingpdf
  stirlingpdf:
    image: frooodle/s-pdf:latest
    container_name: stirlingpdf
    profiles:
      - stirlingpdf
    restart: on-failure:5
    depends_on:
      - caddy
    env_file:
      - ./env/stirlingpdf.env
    volumes:
      - stirlingpdf_config:/configs
      - stirlingpdf_tessdata:/usr/share/tessdata
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true
    read_only: false

volumes:
  stirlingpdf_config:
    name: stirlingpdf_config
  stirlingpdf_tessdata:
    name: stirlingpdf_tessdata