services:
  # it-tools
  it-tools0:
    image: corentinth/it-tools:latest
    container_name: it-tools0
    profiles:
      - it-tools
    restart: on-failure:5
    depends_on:
      - caddy
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.001'
          memory: 20M
  it-tools1:
    image: corentinth/it-tools:latest
    container_name: it-tools1
    profiles:
      - it-tools
    restart: on-failure:5
    depends_on:
      - caddy
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.001'
          memory: 20M
