services:
  # Caddy
  caddy:
    image: caddy:latest
    container_name: caddy
    profiles:
      - caddy
    depends_on:
      main_infrastructure:
        condition: service_completed_successfully
    restart: on-failure:5
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress:/var/www/html:rw
      - caddy_data:/data:rw
      - caddy_config:/config:rw
      - ./caddy/config:/etc/caddy:ro
    networks:
      - infra-network
    env_file:
      - ./caddy/env/caddy.env
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: pidof caddy || exit 1
      interval: 120s
      timeout: 10s
      retries: 3

  caddy_backup:
    image: mazzolino/restic:latest
    container_name: caddy_backup
    profiles:
      - caddy
    depends_on:
      - caddy
    restart: on-failure:5
    env_file:
      - ./caddy/env/caddy_backup.env
    volumes:
      - caddy_backup:/mnt/restic
      - caddy_data:/data:ro
    network_mode: none
    cap_drop:
      - NET_ADMIN
      - NET_RAW

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
  caddy_backup:
    name: caddy_backup
