services:
  # Caddy
  caddy:
    image: caddy:latest
    container_name: caddy
    profiles:
      - caddy
    #user: ${PUID:-1000}:${PGID:-1000} 
    depends_on:
      main_infrastructure:
        condition: service_completed_successfully
    restart: on-failure:5
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress:/var/www/html:rw
      - caddy_data:/data:rw
      - caddy_config:/config:rw
      - ./caddy/config:/etc/caddy:ro
    networks:
      - infra-network
    env_file:
      - ./caddy/env/caddy.env
    #read_only: true
    security_opt:
      - no-new-privileges:true
    #cap_drop:
    #  - ALL
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: pidof caddy || exit 1
      interval: 120s
      timeout: 10s
      retries: 3

  caddy_backup:
    image: mazzolino/restic:latest
    container_name: caddy_backup
    profiles:
      - caddy
    depends_on:
      - caddy
    #user: "${PUID:-1000}:${PGID:-1000}"
    restart: on-failure:5
    env_file:
      - ./caddy/env/caddy_backup.env
    volumes:
      - caddy_backup:/mnt/restic
      - caddy_data:/data:ro
    #  - caddy_backup_cache:/.cache
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
  caddy_backup:
    name: caddy_backup
  caddy_backup_cache:
    name: caddy_backup_cache
    
