services:
  # privatebin
  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    container_name: privatebin
    profiles:
      - privatebin
    restart: on-failure:7
    depends_on:
      - caddy
    volumes:
      - privatebin_data:/srv/data
      - ./config/conf.php:/srv/cfg/conf.php:ro
    environment:
      - TZ=${TZ:-Europe/Paris}
    networks:
      - caddy-tools
    security_opt:
      - no-new-privileges:true
    read_only: true

volumes:
  privatebin_data:
    name: privatebin_data

networks:
  caddy-tools:
    driver: bridge
    name: caddy-tools
