include:
# Main
  - services/main/docker-compose.main.yml 
# WordPress
  - services/wordpress/docker-compose.wordpress.yml
# Caddy
  - services/caddy/docker-compose.caddy.yml
# Dufs
  - services/dufs/docker-compose.dufs.yml
# Gitea
  - services/gitea/docker-compose.gitea.yml
# Homepage
  - services/homepage/docker-compose.homepage.yml
# It-tools
  - services/it-tools/docker-compose.it-tools.yml
# Jellyfin
  - services/jellyfin/docker-compose.jellyfin.yml
# Openssh
  - services/openssh/docker-compose.openssh.yml
# Picoshare
  - services/picoshare/docker-compose.picoshare.yml
# Privatebin
  - services/privatebin/docker-compose.privatebin.yml
# Projectsend
  - services/projectsend/docker-compose.projectsend.yml
# Psitransfer
  - services/psitransfer/docker-compose.psitransfer.yml
# Qbittorrent
  - services/qbittorrent/docker-compose.qbittorrent.yml
# Stirlingpdf
  - services/stirlingpdf/docker-compose.stirlingpdf.yml
# Syncthing
  - services/syncthing/docker-compose.syncthing.yml
# Transmission
  - services/transmission/docker-compose.transmission.yml
# Uptime-kuma
  - services/uptime-kuma/docker-compose.uptime-kuma.yml
# Yacht
  - services/yacht/docker-compose.yacht.yml
# Minecraft
  - services/minecraft-server/minecraft-server/minecraft-server/docker-compose.yml
# Backup minecraft
  - services/minecraft-server/minecraft-server/backup/docker-compose.backup.yml
# 7daystodie
  - services/7daystodie/7daystodie-server/7daystodie/docker-compose.7daystodie.yml
# Backup 7daystodie
  - services/7daystodie/7daystodie-server/backup/docker-compose.backup.yml
