services:
  # transmission
  transmission:
    image: lscr.io/linuxserver/transmission:${TRANSMISSION_DOCKER_TAG:-latest}
    container_name: transmission
    profiles:
      - transmission
    extends:
      file: ../../common.yml
      service: service-base
    depends_on:
      - caddy
    env_file:
      - ./env/transmission.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - transmission_config:/config
      - public_data:/downloads
      - transmission_watch:/watch
    networks:
      - caddy-media

volumes:
  transmission_config:
    name: transmission_config
  transmission_watch:
    name: transmission_watch
  public_data:
    name: public_data
  private_data:
    name: private_data

networks:
  caddy-media:
    driver: bridge
    name: caddy-media