services:
  # transmission
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    profiles:
      - transmission
    restart: on-failure:5
    depends_on:
      - caddy
    env_file:
      - ./env/transmission.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - transmission_config:/config
      - public_data:/downloads
      - transmission_watch:/watch
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true

volumes:
  transmission_config:
    name: transmission_config
  transmission_watch:
    name: transmission_watch
  public_data:
    name: public_data
  private_data:
    name: private_data