services:
  # ghost
  ghost:
    image: ghost:latest
    container_name: ghost
    profiles:
      - ghost
    restart: on-failure:5
    depends_on:
      - ghost_db
      - caddy
    env_file:
      - ./ghost/env/ghost.env
    volumes:
      - ghost_data:/var/lib/ghost/content:rw
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true

  # Database ghost
  ghost_db:
    image: mariadb:latest
    container_name: ghost_db
    profiles:
      - database
      - ghost
    depends_on:
      - caddy
    restart: on-failure:5
    volumes:
      - ghost_db:/var/lib/mysql:rw
    env_file:
      - ./ghost/env/ghost_db.env
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - infra-network
    security_opt:
      - no-new-privileges:true

volumes:
  ghost_db:
    name: ghost_db
  ghost_data:
    name: ghost_data
