services:
  # Watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    profiles:
      - watchtower
    depends_on:
      - caddy
    restart: on-failure:5
    networks:
      - infra-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    security_opt:
      - no-new-privileges:true
