name: infrastructure

on:
  push:
    branches:
      - "main"
      - "master"
      - "dev"
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 9 * * 2" # every tuesday at 9:00 https://crontab.guru/#0_7_*_*_1
  workflow_dispatch:

jobs:
  image:
    name: infrastructure
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: "Update server image"
        run: make update-docker
      - name: "Build server"
        run: make build
#      - name: "Start server"
#        run: make start
      - name: "Logs server"
        run: make logs
      - name: "State server"
        run: make state
      - name: "Stop server"
        run: make stop
      - name: "Down server"
        run: make down
      - name: "Clean server"
        run: make clean
      - name: "Purge server"
        run: make purge